src/exec/end-to-end.ml
This PR starts calling contracts using the hash of function signatures.
The new test testing_00b is not quite working, but I think I should try something simpler first.
=> Function signature

src/codegen/codegen.ml, src/exec/end-to-end.ml
=> Fix return statement

doc/manifest.md
I was reading the manifest and found these typos. Looking forward to learn more about the project
=> fix typos in manifest

.travis.yml, src/ast/type.ml, src/parse/not_working_examples/unknown_type.bbo
=> Refuse unknown types in runtime argument list

src/ast/syntax.ml, src/ast/type.ml, src/codegen/codegen.ml, src/codegen/location.ml, src/codegen/location.mli, src/codegen/locationEnv.ml, src/codegen/locationEnv.mli, src/lib/ethereum.ml, src/parse/examples/00e_ecdsarecover.bbo
=> code generation for ecdsarecover

src/exec/end-to-end.ml
Most time during end-to-end testing was spent on generating new accounts
=> Faster end-to-end test

src/ast/type.ml, src/codegen/codegen.ml, src/exec/end-to-end.ml, src/parse/examples/013_iszero.bbo
=> Implement iszero()

.travis.yml, src/ast/syntax.ml, src/codegen/codegen.ml, src/exec/end-to-end.ml
Adding a test case for closing a payment channel from the receiver side.
Also several bug fixes.
=> Payment early

src/ast/syntax.ml, src/ast/type.ml, src/lib/ethereum.ml
Removing some warnings.
This is a preparation for #36 .
=> Remove some warnings

sketch/open_auction.bbo, src/ast/syntax.ml, src/ast/syntax.mli, src/ast/type.ml, src/codegen/codegen.ml, src/parse/examples/005auction_start.bbo, src/parse/examples/006auction_first_case.bbo, src/parse/examples/007auction_first_case_more.bbo, src/parse/examples/008new_var.bbo, src/parse/examples/009new_var_auc.bbo, src/parse/examples/00a_auc_first_cast.bbo, src/parse/examples/00b_auction_more.bbo, src/parse/examples/00c_auction.bbo, src/parse/examples/00d_auction.bbo, src/parse/examples/00h_payment_channel.bbo, src/parse/examples/018_mapmap.bbo, src/parse/lexer.mll, src/parse/parser.mly
Somehow the code is generated for mappings of mappings.  Still tests need to be added.
=> Mapping to mappings

src/codegen/codegen.ml, src/exec/end-to-end.ml
=> Test mapmap

src/codegen/codegen.ml
=> Skipe seed setup when there is already a non-zero seed

src/ast/syntax.ml, src/ast/syntax.mli, src/ast/type.ml, src/codegen/codegen.ml, src/parse/examples/01b_erc20better.bbo, src/parse/lexer.mll, src/parse/parser.mly
=> Erc20again

Makefile, src/ast/syntax.ml, src/ast/type.ml, src/codegen/codegen.ml, src/codegen/evm.ml, src/lib/ethereum.ml, src/parse/parser.mly
=> Turn all warnings to errors, and fix them

sketch/open_auction.bbo, src/parse/examples/009new_var_auc.bbo, src/parse/examples/00a_auc_first_cast.bbo, src/parse/examples/00b_auction_more.bbo, src/parse/examples/00bbauction_first_named_case.bbo, src/parse/examples/00c_auction.bbo, src/parse/examples/00d_auction.bbo, src/parse/lexer.mll, src/parse/parser.mly
=> Replace `new` with `deploy`

src/ast/type.ml
=> Check that the signatures are unique

src/exec/end-to-end.ml, src/parse/examples/021_land_neq.bbo, src/parse/parser.mly
=> Precedence of && and !=

src/exec/end-to-end.ml, src/parse/examples/020_plus_mult.bbo
=> Add a test about + and *

src/ast/type.ml
=> Reserve names that start with pre_

src/exec/end-to-end.ml, src/parse/examples/01b_erc20better.bbo, src/parse/examples/022_plus_gt.bbo
=> Make sure + connects stronger than <

src/parse/negative_examples/multi_default.bbo
=> Add a negative test about multiple default methods

src/ast/sideEffect.ml, src/ast/sideEffect.mli, src/ast/syntax.ml, src/ast/syntax.mli, src/ast/type.ml, src/ast/typeEnv.ml, src/ast/typeEnv.mli, src/lib/lib_test.ml, src/parse/parser.mly
Detect when a list of arguments contains multiple side-effects that are not read only.
=> Side effects

ReleaseNotes.txt, sketch/open_auction.bbo, src/ast/ethereum.ml, src/ast/syntax.ml, src/ast/syntax.mli, src/ast/type.ml, src/codegen/codegen.ml, src/codegen/codegen_test.ml, src/lib/lib_test.ml, src/parse/examples/004simple_case_abort.bbo, src/parse/examples/005auction_start.bbo, src/parse/examples/006auction_first_case.bbo, src/parse/examples/007auction_first_case_more.bbo, src/parse/examples/008new_var.bbo, src/parse/examples/009new_var_auc.bbo, src/parse/examples/00a_auc_first_cast.bbo, src/parse/examples/00b_auction_more.bbo, src/parse/examples/00bbauction_first_named_case.bbo, src/parse/examples/00c_auction.bbo, src/parse/examples/00d_auction.bbo, src/parse/examples/00h_payment_channel.bbo, src/parse/examples/016_void.bbo, src/parse/examples/019_something.bbo, src/parse/examples/01a_event.bbo, src/parse/examples/01b_erc20better.bbo, src/parse/examples/020_plus_mult.bbo, src/parse/examples/022_plus_gt.bbo, src/parse/lexer.mll, src/parse/negative_examples/wrong_return.bbo, src/parse/parser.mly
=> Say uint256 instead of uint

src/parse/parser.mly
Menhir provides a nice standard library to make parsing delimited and separated lists of nonterminals easier. This PR switches from the reverse-parsing strategy to this library approach, as well as using `inline` definitions to reduce redundancy in the infix operator rules and conditional rules. 
This PR should not affect the grammar of the language in any way.
=> Use Menhir standard library for parser

doc/manifest.md
=> Fix manifest docs

src/exec/endToEnd.ml, src/parse/examples/024_vault_shorter.bbo
and fix `024_vault.bbo` for a bug.
=> Add a test for the happy path for the vault program

doc/spec.tex
This PR defined deploy-expressions in the specification.
=> Define deploy-expressions in spec.tex

src/exec/endToEnd.ml, src/parse/examples/024_vault.bbo, src/parse/examples/024_vault_shorter.bbo
Based on this comment:
https://www.reddit.com/r/ethereum/comments/77ff1l/implementing_a_vault_in_bamboo/doljzqn/
=> Each time unvault() is called, a hot wallet is specified

src/codegen/codegenEnv.ml
=> Error when stack overflows

doc/spec.tex
=> Defining a contract

src/ast/ethereum.ml
=> Ignore empty strings in the list of constructor interfaces

.travis.yml, src/ast/type.ml, src/codegen/codegen.ml, src/run_tests.sh
=> Add tests parsing --abi outputs as JSON
